### PR TITLE
[#14] Correct response codes

### LINKED ISSUE #14: Correct response codes
If database fails to process and it's certainly user's fault - send 500

### PR DESCRIPTION
**Pull request by br3w0r**
Closes #14

### CODE REVIEW

File: util/errors/helpers.go [hunk 1]
```diff
@@ -0,0 +1,21 @@
+package errors
+
+import (
+	"gorm.io/gorm"
+)
+
+func FromGORM(err error, msg string) *Error {
+	var code errorCode
+
+	if err == gorm.ErrRecordNotFound {
```
Comment (br3w0r) [inline util/errors/helpers.go]: Replace with `errors.Is()`

File: util/errors/codes.go [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+		return "INTERNAL"
+	case Timeout:
+		return "TIMEOUT"
+	case Unauthorized:
+		return "UNAUTHORIZED"
+	case AccessDenied:
+		return "ACCESS_DENIED"
+	}
+
+	return "Unknown"
```
Comment (br3w0r) [inline util/errors/codes.go]: Upper case

File: service/gamelist-service.go [hunk 3]
```diff
@@ -142,18 +143,20 @@ func (s *gameListService) CheckLogin(login entity.LoginProfile) (*entity.Profile
 	if err != nil {
 		return nil, err
 	}
+
 	err = bcrypt.CompareHashAndPassword([]byte(profile.Password), []byte(login.Password))
 	if err != nil {
-		return nil, err
+		return nil, utilErrs.New(utilErrs.Unauthorized, err, "hash check failed")
```
Comment (br3w0r) [inline service/gamelist-service.go:149]: Make message less technical. E.g. `incorrect password`

File: service/jwt-service.go [hunk 4]
```diff
@@ -87,7 +87,7 @@ func (s *jwtService) GenerateTokens(user string) (*entity.TokenPair, error) {
 
 	refreshTokenString, err := refreshToken.SignedString(refreshKey)
 	if err != nil {
-		return nil, err
+		return nil, utilErrs.New(utilErrs.Internal, err, "failed to generate token string")
```
Comment (br3w0r) [inline service/jwt-service.go:90]:
```suggestion
		return nil, utilErrs.New(utilErrs.Internal, err, "failed to generate refresh token string")
```
